name: Deploy to GitHub Pages

on:
  # 当推送到 main 分支时触发
  push:
    branches: [ main ]
  # 允许手动触发
  workflow_dispatch:

# 设置权限，允许推送到 gh-pages 分支
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 3. 安装依赖
      - name: Install dependencies
        run: npm ci

      # 4. 构建项目
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          PUBLIC_URL: /ggplotchim

      # 5. 部署到 gh-pages 分支
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages

